/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 model.gltf
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("model.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Line001.geometry}
        material={materials["Material #24"]}
        position={[0.072, 0.022, 0.034]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Line019.geometry}
        material={materials["Material #36"]}
        position={[0.068, -0.073, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Line020.geometry}
        material={materials["Material #36"]}
        position={[0.067, -0.068, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Line023.geometry}
        material={materials.резина}
        position={[0.028, -0.029, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gengon012.geometry}
        material={materials.болты}
        position={[0.037, -0.1, -0.052]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.381}
      />
      <mesh
        geometry={nodes.Gengon011.geometry}
        material={materials.болты}
        position={[0.023, -0.099, -0.052]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.381}
      />
      <mesh
        geometry={nodes.Gengon010.geometry}
        material={materials.болты}
        position={[0.03, -0.088, -0.052]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.381}
      />
      <mesh
        geometry={nodes.Gengon009.geometry}
        material={materials.болты}
        position={[0.037, -0.1, -0.047]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.381}
      />
      <mesh
        geometry={nodes.Gengon007.geometry}
        material={materials.болты}
        position={[0.03, -0.088, -0.047]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.381}
      />
      <mesh
        geometry={nodes.Gengon006.geometry}
        material={materials.болты}
        position={[0.037, -0.1, 0.042]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.381}
      />
      <mesh
        geometry={nodes.Gengon005.geometry}
        material={materials.болты}
        position={[0.023, -0.099, 0.042]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.381}
      />
      <mesh
        geometry={nodes.Gengon004.geometry}
        material={materials.болты}
        position={[0.03, -0.088, 0.042]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.381}
      />
      <mesh
        geometry={nodes.Gengon003.geometry}
        material={materials.болты}
        position={[0.037, -0.1, 0.045]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.381}
      />
      <mesh
        geometry={nodes.Gengon002.geometry}
        material={materials.болты}
        position={[0.023, -0.099, 0.045]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.381}
      />
      <mesh
        geometry={nodes.Gengon001.geometry}
        material={materials.болты}
        position={[0.03, -0.088, 0.045]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.381}
      />
      <mesh
        geometry={nodes.Gengon008.geometry}
        material={materials.болты}
        position={[0.023, -0.099, -0.047]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.381}
      />
      <mesh
        geometry={nodes.Line024.geometry}
        material={materials.резина}
        position={[0.08, 0.022, -0.036]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Capsule002.geometry}
        material={materials.болты}
        position={[0.035, -0.027, 0.038]}
        rotation={[Math.PI / 2, 0, -0.436]}
        scale={0.029}
      />
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={materials.болты}
        position={[0.032, -0.027, 0.032]}
        rotation={[Math.PI / 2, 0, -0.436]}
      />
      <mesh
        geometry={nodes.Spindle003.geometry}
        material={materials.болты}
        position={[0.032, -0.027, 0.032]}
        rotation={[Math.PI / 2, 0, -0.436]}
        scale={0.029}
      />
      <mesh
        geometry={nodes.Capsule003.geometry}
        material={materials.болты}
        position={[0.035, 0.051, 0.038]}
        rotation={[Math.PI / 2, 0, -0.436]}
        scale={0.029}
      />
      <mesh
        geometry={nodes.Cylinder006.geometry}
        material={materials.болты}
        position={[0.032, 0.051, 0.032]}
        rotation={[Math.PI / 2, 0, -0.436]}
      />
      <mesh
        geometry={nodes.Spindle004.geometry}
        material={materials.болты}
        position={[0.032, 0.051, 0.032]}
        rotation={[Math.PI / 2, 0, -0.436]}
        scale={0.029}
      />
      <mesh
        geometry={nodes.Capsule004.geometry}
        material={materials.болты}
        position={[0.033, -0.027, -0.041]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={0.029}
      />
      <mesh
        geometry={nodes.Cylinder007.geometry}
        material={materials.болты}
        position={[0.034, -0.027, -0.035]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.Spindle005.geometry}
        material={materials.болты}
        position={[0.034, -0.027, -0.034]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={0.029}
      />
      <mesh
        geometry={nodes.Capsule005.geometry}
        material={materials.болты}
        position={[0.033, 0.051, -0.041]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={0.029}
      />
      <mesh
        geometry={nodes.Cylinder008.geometry}
        material={materials.болты}
        position={[0.034, 0.051, -0.035]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.Spindle006.geometry}
        material={materials.болты}
        position={[0.034, 0.051, -0.034]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={0.029}
      />
      <mesh
        geometry={nodes.Box003.geometry}
        material={materials["Material #24"]}
        position={[0.037, -0.027, 0.035]}
        rotation={[Math.PI / 2, 0, 1.745]}
      />
      <mesh
        geometry={nodes.Box001.geometry}
        material={materials["Material #24"]}
        position={[0.037, 0.051, 0.035]}
        rotation={[Math.PI / 2, 0, 1.745]}
      />
      <mesh
        geometry={nodes.Box004.geometry}
        material={materials["Material #24"]}
        position={[0.037, -0.027, -0.037]}
        rotation={[Math.PI / 2, 0, -1.745]}
        scale={[1, -1, 1]}
      />
      <mesh
        geometry={nodes.Box002.geometry}
        material={materials["Material #24"]}
        position={[0.037, 0.051, -0.037]}
        rotation={[Math.PI / 2, 0, -1.745]}
        scale={[1, -1, 1]}
      />
      <mesh
        geometry={nodes.Line018.geometry}
        material={materials["Material #24"]}
        position={[0.022, 0.107, 0.001]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Line013.geometry}
        material={materials["Material #41"]}
        position={[0.01, 0.047, -0.022]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials["Material #24"]}
        position={[0.033, 0.12, 0.035]}
        rotation={[0, 1.57, 0]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials["Material #24"]}
        position={[0.033, 0.12, -0.038]}
        rotation={[0, 1.57, 0]}
      />
      <mesh
        geometry={nodes.Line002.geometry}
        material={materials["Material #24"]}
        position={[0.033, 0.163, -0.001]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Tube002.geometry}
        material={materials["Material #24"]}
        position={[0.03, -0.096, 0.032]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Tube001.geometry}
        material={materials["Material #24"]}
        position={[0.03, -0.096, -0.041]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Box005.geometry}
        material={materials.болты}
        position={[0.011, 0.088, 0.006]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Line015.geometry}
        material={materials.красный}
        position={[0.004, 0.084, 0.01]}
      />
      <mesh
        geometry={nodes.Line014.geometry}
        material={materials.красный}
        position={[0.01, 0.087, 0.01]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Line011.geometry}
        material={materials["Material #36"]}
        position={[0.01, 0.071, -0.022]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Shape001.geometry}
        material={materials.красный}
        position={[0.01, 0.078, -0.023]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Cylinder009.geometry}
        material={materials["Material #36"]}
        position={[0.01, 0.084, 0.008]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Spindle007.geometry}
        material={materials.болты}
        position={[0.01, 0.112, 0]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        geometry={nodes.Cylinder010.geometry}
        material={materials.болты}
        position={[0.01, 0.084, 0.011]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Line010.geometry}
        material={materials.черный}
        position={[0.01, 0.078, -0.023]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Line009.geometry}
        material={materials["Material #36"]}
        position={[0.01, 0.08, -0.004]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Line016.geometry}
        material={materials.красный}
        position={[0.017, 0.084, 0.01]}
        rotation={[0, 0, -Math.PI]}
        scale={[1, -1, 1]}
      />
      <mesh
        geometry={nodes.Line017.geometry}
        material={materials["Material #36"]}
        position={[0.017, 0.107, 0.001]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder011.geometry}
        material={materials.черный}
        position={[0.002, 0.068, -0.018]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Line021.geometry}
        material={materials["13 - Default"]}
        position={[0.01, 0.057, -0.019]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.589}
      />
      <mesh
        geometry={nodes.Line022.geometry}
        material={materials["default"]}
        position={[0.01, 0.055, -0.018]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.589}
      />
      <mesh
        geometry={nodes.Cylinder017.geometry}
        material={materials["default"]}
        position={[0, 0.068, -0.018]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Object003.geometry}
        material={materials["Material #27"]}
        position={[0.002, 0.068, -0.018]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Line012.geometry}
        material={materials.красный}
        position={[0.01, 0.12, -0.002]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Заглушка_ножки.geometry}
        material={materials.резина}
        position={[0.063, -0.035, 0.035]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Line003.geometry}
        material={materials["Material #24"]}
        position={[0.063, -0.035, 0.035]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Line004.geometry}
        material={materials["Material #24"]}
        position={[0.063, -0.035, -0.038]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Заглушка_ножки001.geometry}
        material={materials.резина}
        position={[0.063, -0.035, -0.038]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={materials.ось}
        position={[0.03, -0.096, -0.057]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Line006.geometry}
        material={materials.резина}
        position={[0.016, -0.096, 0.045]}
        rotation={[-Math.PI, 0, 0]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.Object001.geometry}
        material={materials.диски}
        position={[0.024, -0.096, 0.048]}
        rotation={[-Math.PI, 0, 0]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.Line005.geometry}
        material={materials.диски}
        position={[0.024, -0.096, 0.048]}
        rotation={[-Math.PI, 0, 0]}
        scale={0.268}
      />
      <mesh
        geometry={nodes.Line007.geometry}
        material={materials.диски}
        position={[0.037, -0.096, -0.045]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.268, -0.268, 0.268]}
      />
      <mesh
        geometry={nodes.Line008.geometry}
        material={materials.резина}
        position={[0.045, -0.096, -0.047]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.268, -0.268, 0.268]}
      />
      <mesh
        geometry={nodes.Object002.geometry}
        material={materials.диски}
        position={[0.037, -0.096, -0.045]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.268, -0.268, 0.268]}
      />
      <mesh
        geometry={nodes.Sphere001.geometry}
        material={materials.болты}
        position={[0.025, 0.236, 0.025]}
        rotation={[-Math.PI / 2, -1.559, 1.571]}
      />
      <mesh
        geometry={nodes.ChamferCyl001.geometry}
        material={materials.ось}
        position={[0.023, 0.218, 0.022]}
        rotation={[-Math.PI / 2, -1.559, 1.571]}
      />
      <mesh
        geometry={nodes.Sphere007.geometry}
        material={materials.болты}
        position={[0.019, 0.214, 0.027]}
        rotation={[0, 0, 3.129]}
      />
      <mesh
        geometry={nodes.Sphere006.geometry}
        material={materials.болты}
        position={[0.026, 0.175, 0.027]}
        rotation={[Math.PI, 0, 0.012]}
      />
      <mesh
        geometry={nodes.Sphere005.geometry}
        material={materials.болты}
        position={[0.026, 0.204, 0.027]}
        rotation={[Math.PI, 0, 0.012]}
      />
      <mesh
        geometry={nodes.Cylinder013.geometry}
        material={materials["default"]}
        position={[0.023, 0.219, 0.022]}
        rotation={[-Math.PI / 2, -1.559, 1.571]}
      />
      <mesh
        geometry={nodes.Cylinder014.geometry}
        material={materials["Material #39"]}
        position={[0.023, 0.23, 0.022]}
        rotation={[-Math.PI / 2, -1.559, 1.571]}
      />
      <mesh
        geometry={nodes.Cylinder015.geometry}
        material={materials.резина}
        position={[0.023, 0.236, 0.022]}
        rotation={[-Math.PI / 2, -1.559, 1.571]}
      />
      <mesh
        geometry={nodes.Cylinder016.geometry}
        material={materials["default"]}
        position={[0.026, 0.211, 0.019]}
        rotation={[-1.571, -1.559, -Math.PI]}
      />
      <mesh
        geometry={nodes["Cylinder015_(1)"].geometry}
        material={materials.болты}
        position={[0.029, 0.211, 0.025]}
        rotation={[-1.571, -1.559, -Math.PI]}
      />
      <mesh
        geometry={nodes.Sphere004.geometry}
        material={materials.болты}
        position={[0.026, 0.175, 0.016]}
        rotation={[Math.PI, 0, 0.012]}
      />
      <mesh
        geometry={nodes.Sphere002.geometry}
        material={materials["default"]}
        position={[0.025, 0.236, 0.019]}
        rotation={[-Math.PI / 2, -1.559, 1.571]}
      />
      <mesh
        geometry={nodes.Sphere003.geometry}
        material={materials.болты}
        position={[0.026, 0.204, 0.016]}
        rotation={[Math.PI, 0, 0.012]}
      />
      <mesh
        geometry={nodes.Sphere008.geometry}
        material={materials.болты}
        position={[0.019, 0.214, 0.016]}
        rotation={[0, 0, 3.129]}
      />
      <mesh
        geometry={nodes.Spindle009.geometry}
        material={materials.болты}
        position={[0.022, 0.161, 0.022]}
        rotation={[-Math.PI / 2, -1.559, Math.PI / 2]}
        scale={0.633}
      />
      <mesh
        geometry={nodes.Spindle008.geometry}
        material={materials.ось}
        position={[0.022, 0.17, 0.022]}
        rotation={[-Math.PI / 2, -1.559, 1.571]}
      />
      <mesh
        geometry={nodes.Cylinder012.geometry}
        material={materials.болты}
        position={[0.022, 0.167, 0.022]}
        rotation={[-Math.PI / 2, -1.559, 1.571]}
      />
      <mesh
        geometry={nodes.Circle001.geometry}
        material={materials["Material #29"]}
        position={[0.048, 0.176, 0.022]}
        rotation={[Math.PI / 2, 0.424, -Math.PI / 2]}
        scale={0.642}
      />
      <mesh
        geometry={nodes.Box006.geometry}
        material={materials.ось}
        position={[0.031, 0.218, 0.022]}
        rotation={[Math.PI / 2, 0.162, -Math.PI / 2]}
      />
    </group>
  );
}

useGLTF.preload("model.gltf");
